title: 'Inklyn'
description: 'No Entrepreneur Left Behind'

url: 'https://inklyn.com'
baseurl: ''

markdown: kramdown

permalink: pretty
permalink: /:title/

feed:
  posts_limit: 10
  author: Inklyn

sass:
  style: compressed
  sourcemap: never

exclude:
  - Gemfile
  - Gemfile.lock
  - README.*